---
title: 
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r Table, echo=FALSE, message=FALSE, warning=FALSE,results="asis"}
library(tidyverse)
library(kableExtra)
df<-data.frame("Research Stage"=c("Questions relevant to stakeholders","Questions relevant to stakeholders","Appropriate design and methods","Appropriate design and methods",
                                  "Appropriate design and methods","Appropriate design and methods","Unbiased reporting","Unbiased reporting","Unbiased reporting","Unbiased reporting",
                                  "Unbiased reporting","Accessible full publication","Evidence synthesis"),
               "Examples of potential for research waste"=c("Irrelevant questions asked","Previous knowledge not properly taken into account","Study poorly designed, under-powered (or over-powered. etc.)",
                                                            "Using inappropriate statistical tools (including overfitting etc.)","Questionable research practices lead to poor quality research","Questionable research practices lead to poor quality research",
                                                            "Lack of open data","Hypothesising after the results are known","p-hacking","File-drawer syndrome (only some studies are published)","Incomplete reporting, making evidence synthesis difficult or impossible",
                                                            "Publications not available to practitioners and decision makers","Research not designed or presented in the context of the existing knowledge"),
               "Where ecology and conservation can reduce waste"=c("Co-development of research questions with stakeholders and using appropriate methodology such as Delphi exercises to avoid issues such as group think or not including the right group of experts or stakeholders",
               "Make use of evidence synthesis methods (e.g. cumulative meta-analysis, systematic mapping, systematic reviews, meta-analysis) to identify questions that are not satisfactorily answered",
               "Use simulations or power-analysis prior to undertaking data collection. Predefine effect size of interest with stakeholders (i.e. do not rely on rules of thumb for “statistical significance”)",
               "Better training of early-career researchers in methods. Open code and data to ensure reproducibility of methods",
               "Open science (open methods and data, reproducible methods, sharing code, etc.)",
               "Better training of early-career researchers in methods of open science and evidence synthesis",
               "Open science (open methods and data, reproducible methods, sharing code, etc.)",
               "Pre-registration of hypotheses", 
               "Open science (open methods and data, reproducible methods, sharing code, etc.)",
               "Pre-registration of hypotheses and methods. Open publishing (including preprints)",
               "Increasing knowledge of researchers and peer reviewers on what is essential to report, and changing journal guidelines where necessary to ensure all relevant information is reported",
               "Open access publishing, including making resources available to researchers to be able to publish open access","Using systematic reviews, systematic maps, meta-analysis, etc. to shape research priorities. Where good quality evidence is available these should be synthesised providing evidence to relevant stakeholders. Research gaps should be the focus of primary studies."
               ))

k<-kable(df,col.names = c("Research stage",
                           "Examples of potential for research waste",
                           "Where ecology and conservation can reduce waste"),booktabs = T, caption = "Table 1. The research process stages (adapted from Chalmers & Glasziou, 2009), examples of potential research waste and how ecology and conservation can limit these.",border_left = T, border_right = T) %>% column_spec(1, bold=T) %>% collapse_rows(columns = 1:3, latex_hline = "major", valign = "middle") %>% kable_styling()
#save_kable(k, "table1.pdf")

```

